razansmadi/razansmadi/Models/Chalet.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace razansmadi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chalet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chalet()
        {
            this.Bookings = new HashSet<Booking>();
            this.CategoriesChalets = new HashSet<CategoriesChalet>();
            this.CategoriesChalets1 = new HashSet<CategoriesChalet>();
            this.Comments = new HashSet<Comment>();
            this.Comments1 = new HashSet<Comment>();
            this.Faves = new HashSet<Fave>();
            this.Faves1 = new HashSet<Fave>();
            this.votes = new HashSet<vote>();
            this.votes1 = new HashSet<vote>();
        }
    
        public int ChaletID { get; set; }
        public string userid { get; set; }
        public string Chalet_Name { get; set; }
        public string Chalet_Description { get; set; }
        public string Chalet_Address { get; set; }
        public Nullable<int> AvailabilityFlag { get; set; }
        public Nullable<int> NnmberOfAdult { get; set; }
        public Nullable<int> NnmberOfkid { get; set; }
        public Nullable<decimal> PricePerNight { get; set; }
        public Nullable<int> Images_ID { get; set; }
        public Nullable<int> Features_ID { get; set; }
        public Nullable<bool> isAccepted { get; set; }
        public Nullable<int> bedroom { get; set; }
        public Nullable<int> bathroom { get; set; }
        public Nullable<double> area { get; set; }
        public Nullable<bool> super { get; set; }
        public string map { get; set; }
        public Nullable<System.DateTime> DateOfReg { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriesChalet> CategoriesChalets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriesChalet> CategoriesChalets1 { get; set; }
        public virtual Feature Feature { get; set; }
        public virtual Image Image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fave> Faves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fave> Faves1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vote> votes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vote> votes1 { get; set; }
    }
}

razansmadi/razansmadi/Controllers/ChaletsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using razansmadi.Models;

namespace razansmadi.Controllers
{
    public class ChaletsController : Controller
    {
        private MasterPieceEntities db = new MasterPieceEntities();

        // GET: Chalets
        public ActionResult Index()
        {
            var chalets = db.Chalets.Include(c => c.AspNetUser).Include(c => c.Feature).Include(c => c.Image).Where(x => x.isAccepted != true);
            return View(chalets.ToList());
        }
        public ActionResult Home()
        {
            var cate = db.Categories.ToList();
            var chalets = db.Chalets.Include(c => c.AspNetUser).Include(c => c.Feature).Include(c => c.Image).Where(x => x.super == true && x.isAccepted==true).ToList();
            var images = (from c in chalets
                          join i in db.Images on c.Images_ID equals i.Images_ID
                          select i).ToList();

            var features = (from c in chalets
                          join i in db.Features on c.Features_ID equals i.Features_ID
                          select i).ToList();

            var data = Tuple.Create(chalets, cate, images, features);

            return View(data);
        }


        public ActionResult about() { return View(); }
        public ActionResult contact() { return View(); }


        public ActionResult AllChalet(string sortOrder, string address, string category)
        {
            var chalets = db.Chalets.Include(c => c.AspNetUser).Include(c => c.Feature).Include(c => c.Image);

            // Filter by address
            if (!string.IsNullOrEmpty(address))
            {
                chalets = chalets.Where(c => c.Chalet_Address == address);
            }

            // Filter by category
            if (!string.IsNullOrEmpty(category))
            {
                chalets = chalets.Where(c => c.CategoriesChalets.Any(cc => cc.Category.Category_Name == category));
            }

            // Sort by price
            if (sortOrder == "priceDesc")
            {
                chalets = chalets.OrderByDescending(c => c.PricePerNight);
            }
            else if (sortOrder == "priceAsc")
            {
                chalets = chalets.OrderBy(c => c.PricePerNight);
            }

            var categories = db.Categories.ToList();

            // Get all unique addresses and categories
            var uniqueAddresses = chalets.Select(c => c.Chalet_Address).Distinct().ToList();
            var uniqueCategories = categories.Select(c => c.Category_Name).Distinct().ToList();

            ViewBag.AddressList = db.Chalets.Where(c => c.Chalet_Address != null)
                                             .Select(c => c.Chalet_Address)
                                             .Distinct()
                                             .ToList();
            ViewBag.CategoryList = categories.Select(cat => cat.Category_Name).Distinct().ToList();

            var data = Tuple.Create(chalets.ToList(), categories, uniqueAddresses, uniqueCategories);
            return View(data);

        }

        [HttpPost]
        public ActionResult UpdateIsAccepted(int itemId, bool? isAccepted)
        {
            // Retrieve the item from the database using the item ID.
            var item = db.Chalets.Find(itemId);

            // Update the "isAccepted" property of the item.
            item.isAccepted = isAccepted;

            // Save the changes to the database.
            db.SaveChanges();

            // Redirect the user back to the index page.
            return RedirectToAction("Index");
        }


        public ActionResult ChaletDetails(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var chalet = db.Chalets.Find(id);
            if (chalet == null)
            {
                return HttpNotFound();
            }

            var images = db.Images.Where(i => i.Images_ID == chalet.Images_ID).ToList();
            var features = db.Features.Where(f => f.Features_ID == chalet.Features_ID).ToList();
            var user = db.AspNetUsers.FirstOrDefault(f => f.Id == chalet.userid);
            var data = Tuple.Create(user, chalet, features, images);
            return View(data);
        }





        public ActionResult acceptedChalet()
        {
            var chalets = db.Chalets.Include(c => c.AspNetUser).Include(c => c.Feature).Include(c => c.Image).Where(x=>x.isAccepted==true);
            return View(chalets.ToList());

        }

        public ActionResult acceptedDetail(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chalet chalet = db.Chalets.Find(id);
            if (chalet == null)
            {
                return HttpNotFound();
            }
            return View(chalet);
        }

  

        // GET: Chalets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chalet chalet = db.Chalets.Find(id);
            if (chalet == null)
            {
                return HttpNotFound();
            }
            return View(chalet);
        }

        // GET: Chalets/Create
        public ActionResult Create()
        {
            ViewBag.userid = new SelectList(db.AspNetUsers, "Id", "Email");
            ViewBag.Features_ID = new SelectList(db.Features, "Features_ID", "Features_ID");
            ViewBag.Images_ID = new SelectList(db.Images, "Images_ID", "MainImage");
            return View();
        }

        // POST: Chalets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ChaletID,userid,Chalet_Name,Chalet_Description,Chalet_Address,AvailabilityFlag,NnmberOfAdult,NnmberOfkid,PricePerNight,Images_ID,Features_ID,isAccepted,bedroom,bathroom,area")] Chalet chalet)
        {
            if (ModelState.IsValid)
            {
                db.Chalets.Add(chalet);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.userid = new SelectList(db.AspNetUsers, "Id", "Email", chalet.userid);
            ViewBag.Features_ID = new SelectList(db.Features, "Features_ID", "Features_ID", chalet.Features_ID);
            ViewBag.Images_ID = new SelectList(db.Images, "Images_ID", "MainImage", chalet.Images_ID);
            return View(chalet);
        }























        // GET: Chalets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chalet chalet = db.Chalets.Find(id);
            if (chalet == null)
            {
                return HttpNotFound();
            }
            ViewBag.userid = new SelectList(db.AspNetUsers, "Id", "Email", chalet.userid);
            ViewBag.Features_ID = new SelectList(db.Features, "Features_ID", "Features_ID", chalet.Features_ID);
            ViewBag.Images_ID = new SelectList(db.Images, "Images_ID", "MainImage", chalet.Images_ID);
            return View(chalet);
        }

        // POST: Chalets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, [Bind(Include = "ChaletID,userid,Chalet_Name,Chalet_Description,Chalet_Address,AvailabilityFlag,NnmberOfAdult,NnmberOfkid,PricePerNight,Images_ID,Features_ID,isAccepted,bedroom,bathroom,area")] Chalet chalet)
        {
            if (ModelState.IsValid)
            {
                db.Entry(chalet).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("/Index");
            }
            ViewBag.userid = new SelectList(db.AspNetUsers, "Id", "Email", chalet.userid);
            ViewBag.Features_ID = new SelectList(db.Features, "Features_ID", "Features_ID", chalet.Features_ID);
            ViewBag.Images_ID = new SelectList(db.Images, "Images_ID", "MainImage", chalet.Images_ID);
            return View(chalet);
        }
       
        // GET: Chalets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chalet chalet = db.Chalets.Find(id);
            if (chalet == null)
            {
                return HttpNotFound();
            }
            return View(chalet);
        }

        // POST: Chalets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Chalet chalet = db.Chalets.Find(id);
            db.Chalets.Remove(chalet);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult AddComment(int ChaletID, string comment1, string returnUrl)
        {
            Comment comment = new Comment()
            {
                userid = User.Identity.GetUserId(),
                ChaletID = ChaletID,
                Comment_Date = DateTime.Now.Date,
                comment1 = comment1

        };
            db.Comments.Add(comment);

razansmadi/razansmadi/Views/Chalets/AllChalet.cshtml
@model Tuple<List<razansmadi.Models.Chalet>, List<razansmadi.Models.Category>, List<string>, List<string>>

@{
    Layout = null;
}
@using razansmadi.Models

<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Aler Template">
    <meta name="keywords" content="Aler, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Aler | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700,800,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,900&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Babylonica&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <!-- Css Styles -->
    <link rel="stylesheet" href="~/template/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="~/template/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="~/template/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/template/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="~/template/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="~/template/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="~/template/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="~/template/css/magnific-popup.css" type="text/css">
    <link rel="stylesheet" href="~/template/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="~/template/css/style.css" type="text/css">
    <script src="https://kit.fontawesome.com/a8b56cb52b.js" crossorigin="anonymous"></script>
</head>

<body>


    <!-- Offcanvas Menu Wrapper Begin -->
    <div class="offcanvas-menu-overlay"></div>
    <div class="offcanvas-menu-wrapper">
        <div class="canvas-close">
            <span class="icon_close"></span>
        </div>
        <div class="logo">
            <a href="./index.html">
                <span style="font-family: 'Babylonica', cursive;font-weight: bolder;font-size:35px;color:#053503;">Royal Chalets</span>
            </a>
        </div>
        <div id="mobile-menu-wrap"></div>
        <div class="om-social">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-instagram"></i></a>
        </div>
    </div>
    <!-- Offcanvas Menu Wrapper End -->
    <!-- Header Section Begin -->
    <header class="header-section">
        <nav class="navbar navbar-expand-lg ">
            <div class="container-fluid">
                <span style="font-family: 'Babylonica', cursive;font-weight: bolder;font-size:30px;color:#053503;">Royal Chalets</span>

                <button class="navbar-toggler  d-lg-none  d-sm-block" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" style="color: #0A6506; display: flex; justify-content: center;">
                    <i class="fa-solid fa-bars"></i>
                </button>

                <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                    <div class="navbar-nav">
                        <a href="./index.html" class="nav-link" style="color: #0A6506; ">Home</a>
                        <a href="./Our Chalets.html" class="nav-link" style="color: #0A6506; border-bottom: 2px solid #0A6506;">Chalets</a>
                        <a href="./profile.html" class="nav-link" style="color: #0A6506;">Profile</a>
                        <a href="./about.html" class="nav-link" style="color: #0A6506;">About</a>
                        <a href="./contact.html" class="nav-link" style="color: #0A6506;">Contact</a>
                        @Html.Partial("_LoginPartial")
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <!-- Header End -->
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section spad set-bg" data-setbg="@Url.Content("~/img/beautiful-park.jpg")">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb-text">
                        <h4>Our Chalets</h4>
                        <div class="bt-option">
                            <a href="Home"><i class="fa fa-home"></i> Home</a>
                            <span>Chalets</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->
    <!-- Property Section Begin -->
    <section class="property-section spad">
        <div class="container">

            <!-- Search Section Begin -->
            <section class="search-section spad">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-7">
                            <div class="section-title">
                                <h4>Enjoy the beauty of Jerash's nature!</h4>
                            </div>
                        </div>
                    </div>

                    <form action="@Url.Action("AllChalet", "Chalets")" method="get" class="filter-form">

                        <div class="d-flex justify-content-around">
                            <select class="sm-width col-4" name="sortOrder" style="justify-content:space-between">
                                <option value="priceDesc">Price From High To Low</option>
                                <option value="priceAsc">Price From Low To High</option>
                            </select>
                            <select class="col-2 " name="address" style="justify-content:space-between">
                                <option value="">All Addresses</option>
                                @foreach (var address in ViewBag.AddressList)
                                {
                                    <option value="@address">@address</option>
                                }
                            </select>

                            <select class="col-2" name="category" style="justify-content:space-between">
                                <option value="">All Categories</option>
                                @foreach (var category in ViewBag.CategoryList)
                                {
                                    <option value="@category">@category</option>
                                }
                            </select>



                            <button type="submit" class="btn btn-success col-2">Search</button>

                        </div>

                    </form>


                </div>


            </section>


            <!-- Search Section End -->
            <!-- Property Section start -->

            <div class="row">
                @foreach (var item in Model.Item1)
                {

                    var db = new MasterPieceEntities();
                    var Image = db.Images.Where(i => i.Images_ID == item.Images_ID).ToList();
                   

                    <div class="col-lg-4 col-md-6 mix all house">
                        <div class="property-item">
                            @foreach (var img in Image)
                            {
                             <img src="~/img/MainImage/@img.MainImage" class="pi-pic set-bg"  />
                            }

                            <div class="pi-text">
                                <a href="#" class="heart-icon"><span class="icon_heart_alt"></span></a>
                                <div class="pt-price">Start From @item.PricePerNight JD /Day </div>
                                <h5><a href="#">@item.Chalet_Name</a></h5>
                                <p><span class="icon_pin_alt"></span> @item.Chalet_Address</p>
                                <ul>
                                    <li><i class="fa fa-object-group"></i> @item.area</li>
                                    <li><i class="fa fa-bathtub"></i> @item.bathroom</li>
                                    <li><i class="fa fa-bed"></i> @item.bedroom</li>
                                    <li><i class="fa fa-automobile"></i> 3</li>
                                </ul>
                                <div class="pi-agent">
                                    <div class="pa-item">
                                        <div class="pa-info">
                                            <img src="img/property/posted-by/pb-1.jpg" alt="">

                                            <h6>Razan</h6>
                                        </div>
                                        <div class="pa-text">
                                            0772267702
                                        </div>
                                    </div>
                                    <br>
                                    <a href="@Url.Action("ChaletDetails", "Chalets", new { id = item.ChaletID })" class="button_header">View More Details</a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </section>
    <!-- Property Section End -->
    <!-- Footer Section Begin -->
    <footer class="footer-section">
        <div class="container">
            <div class="d-flex justify-content-between ">
                <div class="col-lg-4 col-md-6">
                    <div class="fs-about">
                        <div class="fs-logo">
                            <a href="#">
                                <span style="font-family: 'Babylonica', cursive;font-weight: bolder;font-size:70px;color:#053503;">Royal Chalets</span>
                            </a>
                        </div>
                        <p>
                            Comfortable and convenient to Enjoy the beauty of Jerash's stunning nature
                        </p>
                        <div class="fs-social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 d-none d-md-block">
                    <div class="fs-widget">
                        <h5>Links</h5>
                        <div class="d-flex">
                            <ul class="col-6">
                                <li><a href="#">Contact us</a></li>
                                <li><a href="#">About us</a></li>
                                <li><a href="#">Register</a></li>
                            </ul>
                            <ul class="col-6">
                                <li><a href="#">All Chalets</a></li>
                                <li><a href="#">Rent your Chalets</a></li>
                                <li><a href="#">Login</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="d-block d-sm-none">
                    <div class="fs-widget">
                        <h5 class="d-flex justify-content-center">Links</h5>
                        <div class="d-flex">
                            <ul class="col-6">
                                <li><a href="#">Contact</a></li>
                                <li><a href="#">About</a></li>
                                <li><a href="#">Register</a></li>
                                <li><a href="#">Chalets</a></li>
                                <li><a href="#">Login</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
            <div class="copyright-text">
                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> All rights reserved.
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->
    <!-- Js Plugins -->
    <script src="~/template/js/jquery-3.3.1.min.js"></script>
    <script src="~/template/js/bootstrap.min.js"></script>
    <script src="~/template/js/jquery.magnific-popup.min.js"></script>
    <script src="~/template/js/mixitup.min.js"></script>
    <script src="~/template/js/jquery-ui.min.js"></script>
    <script src="~/template/js/jquery.nice-select.min.js"></script>
    <script src="~/template/js/jquery.slicknav.js"></script>
    <script src="~/template/js/owl.carousel.min.js"></script>
    <script src="~/template/js/jquery.richtext.min.js"></script>
    <script src="~/template/js/image-uploader.min.js"></script>
    <script src="~/template/js/main.js"></script>
</body>

</html>

razansmadi/razansmadi/Views/Chalets/Delete.cshtml
@model razansmadi.Models.Chalet

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Chalet</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Chalet_Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Chalet_Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Chalet_Description)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Chalet_Description)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Chalet_Address)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Chalet_Address)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.AvailabilityFlag)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.AvailabilityFlag)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.NnmberOfAdult)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.NnmberOfAdult)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.NnmberOfkid)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.NnmberOfkid)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.PricePerNight)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.PricePerNight)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.isAccepted)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.isAccepted)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.AspNetUser.Email)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.AspNetUser.Email)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Feature.Features_ID)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Feature.Features_ID)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Image.MainImage)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Image.MainImage)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>