razansmadi/razansmadi/Controllers/SubAdminChaletsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using razansmadi.Models;
namespace razansmadi.Controllers
{
    public class SubAdminChaletsController : Controller
    {
        private MasterPieceEntities db = new MasterPieceEntities();

        // GET: SubAdminChalets
        public ActionResult Index()
        {
            Update();
            string id= User.Identity.GetUserId();
            ViewBag.OwnerID = id;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser user = db.AspNetUsers.Find(id);

            var chalets = db.Chalets
                .Include(c => c.Feature)
                .Include(c => c.Image)
                .Where(c => c.userid == user.Id)
                .ToList();

            //var ImgIds = chalets.Select(c => c.Images_ID).ToList();
            List<string> images = new List<string>();
            foreach (var chal in chalets)
            {
                int chalId =Convert.ToInt32( chal.Images_ID);
                var image = db.Images.Where(x => x.Images_ID == chalId).Select(x => x.MainImage).FirstOrDefault();
                images.Add(image);
            }
          
            
            //var mainImages = db.Images.Where(i => ImgIds.Contains(i.Images_ID)).Select(i=>i.MainImage).ToList();
            var data = Tuple.Create(chalets, images);
            return View(data);

        }

      
        //create images
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateImg([Bind(Include = "Images_ID,MainImage,poolImage,gardenImage,playGroundImage,roomImage,kitchenImage,livingRoomImage,bathroomImage,viewImage,randomImage")] Image image)
        {
            if (ModelState.IsValid)
            {
                db.Images.Add(image);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(image);
        }
     
        // POST: AspNetUsers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditProfile([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName,FirstName,LastName,Customer_Img")] AspNetUser aspNetUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aspNetUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(aspNetUser);
        }
     

        // GET: SubAdminChalets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chalet chalet = db.Chalets.Find(id);
            if (chalet == null)
            {
                return HttpNotFound();
            }
            return View(chalet);
        }

        // GET: SubAdminChalets/Create
        public ActionResult Create()
        {
            ViewBag.userid = new SelectList(db.AspNetUsers, "Id", "Email");
            ViewBag.Features_ID = new SelectList(db.Features, "Features_ID", "Features_ID");
            ViewBag.Images_ID = new SelectList(db.Images, "Images_ID", "MainImage");
            return View();
        }

        // POST: SubAdminChalets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ChaletID, userid, Features_ID, Images_ID, Chalet_Name, Chalet_Description, Chalet_Address, AvailabilityFlag, NnmberOfAdult, NnmberOfkid, PricePerNight, isAccepted, bedroom, bathroom, area, super, map, DateOfReg")] Chalet chalet)
        {
            if (ModelState.IsValid)
            {
                int? ChaletID = Session["ChaletID"] as int?;
                if (ChaletID != null)
                {
                    chalet.ChaletID = (int)ChaletID;
                }
                else
                {
                    // Handle the case where the featuresId value is null
                }

                int? Features_ID = Session["Features_ID"] as int?;

                if (Features_ID != null)
                {
                    chalet.Features_ID = Features_ID;
                }
                else
                {
                    // Handle the case where the featuresId value is null
                }

                int? Images_ID = Session["Images_ID"] as int?;

                if (Images_ID != null)
                {
                    chalet.Images_ID = Images_ID;

                }
                else
                {
                    // Handle the case where the featuresId value is null
                }

                db.Chalets.Add(chalet);
                db.SaveChanges();
                return RedirectToAction("/Index");
            }

            ViewBag.userid = new SelectList(db.AspNetUsers, "Id", "Email", chalet.userid);
            ViewBag.Features_ID = new SelectList(db.Features, "Features_ID", "Features_ID", chalet.Features_ID);
            ViewBag.Images_ID = new SelectList(db.Images, "Images_ID", "MainImage", chalet.Images_ID);
            return View(chalet);


        }

        public ActionResult CreateDetails()
        {
            ViewBag.userid = new SelectList(db.AspNetUsers, "Id", "Email");
            ViewBag.Features_ID = new SelectList(db.Features, "Features_ID", "Features_ID");
            ViewBag.Images_ID = new SelectList(db.Images, "Images_ID", "MainImage");
            return View();
        }

        // POST: Chalets1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateDetails([Bind(Include = "ChaletID,userid,Features_ID,Images_ID,Chalet_Name,Chalet_Description,Chalet_Address,AvailabilityFlag,NnmberOfAdult,NnmberOfkid,PricePerNight,isAccepted,bedroom,bathroom,area,super,map,DateOfReg")] Chalet chalet)
        {
            if (ModelState.IsValid)
            {
                chalet.userid= User.Identity.GetUserId();
                db.Chalets.Add(chalet);
                db.SaveChanges();

                // add the ID value to the view model
                chalet.ChaletID = db.Entry(chalet).Entity.ChaletID;

                // store the ID in the session
                Session["ChaletID"] = chalet.ChaletID;

                return RedirectToAction("ADD", new { Id = chalet.ChaletID });
            }

            chalet.DateOfReg = DateTime.Today;
            ViewBag.userid = new SelectList(db.AspNetUsers, "Id", "Email", chalet.userid);

            return View(chalet);
        }

        // GET: SubAdminChalets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chalet chalet = db.Chalets.Find(id);
            if (chalet == null)
            {
                return HttpNotFound();
            }
            ViewBag.userid = new SelectList(db.AspNetUsers, "Id", "Email", chalet.userid);
            ViewBag.Features_ID = new SelectList(db.Features, "Features_ID", "Features_ID", chalet.Features_ID);
            ViewBag.Images_ID = new SelectList(db.Images, "Images_ID", "MainImage", chalet.Images_ID);
            return View(chalet);
        }

        // POST: SubAdminChalets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ChaletID,userid,Chalet_Name,Chalet_Description,Chalet_Address,AvailabilityFlag,NnmberOfAdult,NnmberOfkid,PricePerNight,Images_ID,Features_ID,isAccepted,bedroom,bathroom,area,map")] Chalet chalet)
        {
            if (ModelState.IsValid)
            {
                db.Entry(chalet).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("/Index");
            }
            ViewBag.userid = new SelectList(db.AspNetUsers, "Id", "Email", chalet.userid);
            ViewBag.Features_ID = new SelectList(db.Features, "Features_ID", "Features_ID", chalet.Features_ID);
            ViewBag.Images_ID = new SelectList(db.Images, "Images_ID", "MainImage", chalet.Images_ID);
            return View(chalet);
        }


        public ActionResult ADD(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chalet chalet = db.Chalets.Find(id);
            if (chalet == null)
            {
                return HttpNotFound();
            }
            ViewBag.userid = new SelectList(db.AspNetUsers, "Id", "Email", chalet.userid);
            ViewBag.Features_ID = new SelectList(db.Features, "Features_ID", "Features_ID", chalet.Features_ID);
            ViewBag.Images_ID = new SelectList(db.Images, "Images_ID", "MainImage", chalet.Images_ID);
            

            return View(chalet);
        }

        public ActionResult BigAdd(int id)
        { 

razansmadi/razansmadi/Views/SubAdminChalets/ADD.cshtml
@model razansmadi.Models.Chalet
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_OwnersLayout.cshtml";
}
<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header">
            <div class="row">
                <div class="col-sm-12">
                    <h3 class="page-title">Create New Chalet</h3>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">

                        @using (Html.BeginForm("ADD", "SubAdminChalets", FormMethod.Post))
                        {@Html.AntiForgeryToken()


                        <div class="form-group">
                            <div class="col-md-10">
                                <a href="/SubAdminChalets/CreateDetails">Add Detals For Your Chalet</a>
                            </div>
                        </div>

                        @Html.HiddenFor(model => model.ChaletID)

                        <div class="form-group">
                            <div class="col-md-10">
                                <a href="/Images/Create">Add Images For Your Chalet</a>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-10 form-group">
                                <a href="/Features/Create">Add Features For Your Chalet</a>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <a href="@Url.Action("BigAdd", new {id=Model.ChaletID })">Create </a>
                                @*<input type="submit" value="Create" class="btn btn-default" />*@
                            </div>
                        </div>

                        <a href="~/SubAdminChalets/Index">Back to list</a>
                    }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

razansmadi/razansmadi/Views/SubAdminChalets/Create.cshtml
@model razansmadi.Models.Chalet
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_OwnersLayout.cshtml";
}
<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header">
            <div class="row">
                <div class="col-sm-12">
                    <h3 class="page-title">Create New Chalet</h3>

                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        @using (Html.BeginForm(new { id = "myForm" }))
                        {



                            @Html.AntiForgeryToken()
                            @Html.HiddenFor(model => model.userid)
                            <div class="form-group">
                                <div class="col-md-10">
                                    <a href="/SubAdminChalets/CreateDetails">Add Detals For Your Chalet</a>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-10">
                                    <a href="/Images/Create">Add Images For Your Chalet</a>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-10 form-group">
                                    <a href="/Features/Create">Add Features For Your Chalet</a>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Create" class="btn btn-default" />
                                </div>
                            </div>

                            <a href="~/SubAdminChalets/Index">Back to list</a>
                        }

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@*<script>
    const myForm = document.getElementById('myForm');
    myForm.addEventListener('submit', function (event) {
    event.preventDefault(); // prevent form submission to server
            // save form inputs to local storage
            localStorage.setItem('chalet_name', myForm.elements.chalet_name.value);
            localStorage.setItem('location', myForm.elements.location.value);
            localStorage.setItem('Chalet_Description', myForm.elements.Chalet_Description.value);
            localStorage.setItem('NnmberOfAdult', myForm.elements.NnmberOfAdult.value);
            localStorage.setItem('map', myForm.elements.map.value);
            localStorage.setItem('area', myForm.elements.area.value);
            localStorage.setItem('bathroom', myForm.elements.bathroom.value);
            localStorage.setItem('bedroom', myForm.elements.bedroom.value);
            localStorage.setItem('PricePerNight', myForm.elements.PricePerNight.value);
            localStorage.setItem('NnmberOfkid', myForm.elements.NnmberOfkid.value);

            window.location.href = '/Features/Create';
            window.location.href = '/Images/Create';
        });
        // set input values from local storage when page loads
        myForm.elements.chalet_name.value = localStorage.getItem('chalet_name');
        myForm.elements.location.value = localStorage.getItem('location');
        myForm.elements.Chalet_Description.value = localStorage.getItem('Chalet_Description');
        myForm.elements.NnmberOfAdult.value = localStorage.getItem('NnmberOfAdult');
        myForm.elements.map.value = localStorage.getItem('map');
        myForm.elements.area.value = localStorage.getItem('area');
        myForm.elements.bathroom.value = localStorage.getItem('bathroom');
        myForm.elements.bedroom.value = localStorage.getItem('bedroom');
        myForm.elements.PricePerNight.value = localStorage.getItem('PricePerNight');
        myForm.elements.NnmberOfkid.value = localStorage.getItem('NnmberOfkid');
    </script>*@
@*<script>
    var formData = JSON.parse(localStorage.getItem("formData"));
    if (formData) {
        document.getElementById("Chalet_Name").value = formData.Chalet_Name;
        document.getElementById("Chalet_Description").value = formData.Chalet_Description;
        // add code to populate the rest of the form fields from formData as needed
    }

    var myForm = document.getElementById("myForm");
    myForm.addEventListener("submit", function (event) {
        event.preventDefault();
        formData.Chalet_Name = document.getElementById("Chalet_Name").value;
        formData.Chalet_Description = document.getElementById("Chalet_Description").value;
        // add the rest of the form values to formData as needed
        localStorage.setItem("formData", JSON.stringify(formData));
        window.location.href = event.submitter.id === "submitButton" ? "/Images/Create" : "/Features/Create";
    });
</script>

<script>
    var formData = JSON.parse(localStorage.getItem("formData"));
    // use the formData object to populate the form fields on the next page as needed
</script>*@

razansmadi/razansmadi/Views/SubAdminChalets/CreateDetails.cshtml
@model razansmadi.Models.Chalet
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_OwnersLayout.cshtml";
}
<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header">
            <div class="row">
                <div class="col-sm-12">
                    <h3 class="page-title">Add Chalet Details</h3>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()
                            @Html.HiddenFor(model => model.userid)

                            <div class="form-group">
                                Chalet Name
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Chalet_Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Chalet_Name, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                Description
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Chalet_Description, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Chalet_Description, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                Address
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Chalet_Address, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Chalet_Address, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                Nnmber Of Adult
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.NnmberOfAdult, new { htmlAttributes = new { @class = "form-control", min = 1 } })
                                    @Html.ValidationMessageFor(model => model.NnmberOfAdult, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                Nnmber Of kid
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.NnmberOfkid, new { htmlAttributes = new { @class = "form-control", min = 0 } })
                                    @Html.ValidationMessageFor(model => model.NnmberOfkid, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                Price Per Night
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.PricePerNight, new { htmlAttributes = new { @class = "form-control", min = 10 } })
                                    @Html.ValidationMessageFor(model => model.PricePerNight, "", new { @class = "text-danger" })
                                </div>
                            </div>


                            <div class="form-group">
                                bedroom
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.bedroom, new { htmlAttributes = new { @class = "form-control", min = 1 } })
                                    @Html.ValidationMessageFor(model => model.bedroom, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                bathroom
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.bathroom, new { htmlAttributes = new { @class = "form-control", min = 1 } })
                                    @Html.ValidationMessageFor(model => model.bathroom, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                area
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.area, new { htmlAttributes = new { @class = "form-control", min = 100 } })
                                    @Html.ValidationMessageFor(model => model.area, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                Map
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.map, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.map, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Create" class="btn btn-default" />
                                </div>
                            </div>

                            <a href="~/SubAdminChalets/Index">Back to list</a>
                        }

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

razansmadi/razansmadi/Views/SubAdminChalets/Delete.cshtml
@model razansmadi.Models.Chalet

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_OwnersLayout.cshtml";
}

<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header">
            <h2>Details</h2>
            <div class="row">
                <div class="col-sm-12">
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Owners</a></li>
                        <li class="breadcrumb-item active">Details</li>
                    </ul>
                </div>
            </div>
        </div>
        <div>
            <div>
                <div class="form-group">
                    Chalet Name
                    <div class="form-control">
                        @Html.DisplayFor(model => model.Chalet_Name)
                    </div>
                </div>
                <div class="form-group">
                    Chalet Description
                    <div class="form-control">
                        @Html.DisplayFor(model => model.Chalet_Description)
                    </div>
                </div>

                <div class="form-group">
                    Chalet Address
                    <div class="form-control">
                        @Html.DisplayFor(model => model.Chalet_Address)
                    </div>
                </div>


                <div class="form-group">
                    Number Of Adult
                    <div class="form-control">
                        @Html.DisplayFor(model => model.NnmberOfAdult)
                    </div>
                </div>


                <div class="form-group">
                    Number Of kid
                    <div class="form-control">
                        @Html.DisplayFor(model => model.NnmberOfkid)
                    </div>
                </div>
                <div class="form-group">
                    Price Per Night
                    <div class="form-control">
                        @Html.DisplayFor(model => model.PricePerNight)
                    </div>
                </div>
                <div class="form-group">
                    bedroom
                    <div class="form-control">
                        @Html.DisplayFor(model => model.bedroom)
                    </div>
                </div>

                <div class="form-group">
                    bathroom
                    <div class="form-control">
                        @Html.DisplayFor(model => model.bathroom)
                    </div>
                </div>
                <div class="form-group">
                    Area
                    <div class="form-control">
                        @Html.DisplayFor(model => model.area)
                    </div>
                </div>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-danger" />
                    </div>
                }
            </div>
            <br />
        </div>
        <a href="~/SubAdminChalets/Index">Back to list</a>
    </div>
    <br />
</div>

razansmadi/razansmadi/Views/SubAdminChalets/Details.cshtml
@model razansmadi.Models.Chalet

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_OwnersLayout.cshtml";
}

<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header">
            <div class="row">
                <div class="col-sm-12">
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item active">Chalet Details</li>
                    </ul>
                </div>
            </div>
        </div>

        <div>
            <div>

                <div class="form-group">
                    Chalet Name
                    <div class="form-control">
                        @Html.DisplayFor(model => model.Chalet_Name)
                    </div>
                </div>
                <div class="form-group">
                    Chalet Description
                    <div class="form-control">
                        @Html.DisplayFor(model => model.Chalet_Description)
                    </div>
                </div>

                <div class="form-group">
                    Chalet Address
                    <div class="form-control">
                        @Html.DisplayFor(model => model.Chalet_Address)
                    </div>
                </div>


                <div class="form-group">
                    Number Of Adult
                    <div class="form-control">
                        @Html.DisplayFor(model => model.NnmberOfAdult)
                    </div>
                </div>


                <div class="form-group">
                    Number Of kid
                    <div class="form-control">
                        @Html.DisplayFor(model => model.NnmberOfkid)
                    </div>
                </div>
                <div class="form-group">
                    Price Per Night
                    <div class="form-control">
                        @Html.DisplayFor(model => model.PricePerNight)
                    </div>
                </div>
                <div class="form-group">
                    bedroom
                    <div class="form-control">
                        @Html.DisplayFor(model => model.bedroom)
                    </div>
                </div>

                <div class="form-group">
                    bathroom
                    <div class="form-control">
                        @Html.DisplayFor(model => model.bathroom)
                    </div>
                </div>
                <div class="form-group">
                    Area
                    <div class="form-control">
                        @Html.DisplayFor(model => model.area)
                    </div>
                </div>
            </div>

            <br />
        </div>
        <p>
            <a href="~/SubAdminChalets/Index">Back to list</a>
        </p>
    </div>
    <br />
</div>