razansmadi/razansmadi/Models/AspNetUser.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace razansmadi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.AspNetUserRoles = new HashSet<AspNetUserRole>();
            this.Bookings = new HashSet<Booking>();
            this.Chalets = new HashSet<Chalet>();
            this.Comments = new HashSet<Comment>();
            this.Faves = new HashSet<Fave>();
            this.transactions = new HashSet<transaction>();
            this.votes = new HashSet<vote>();
            this.transactions1 = new HashSet<transaction>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Customer_Img { get; set; }
        public Nullable<int> Phone { get; set; }
        public Nullable<bool> donePay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserRole> AspNetUserRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chalet> Chalets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fave> Faves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaction> transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vote> votes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaction> transactions1 { get; set; }
    }
}

razansmadi/razansmadi/Controllers/AspNetUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using razansmadi.Models;

namespace razansmadi.Controllers
{
    public class AspNetUsersController : Controller
    {
        private MasterPieceEntities db = new MasterPieceEntities();

        // GET: AspNetUsers
        public ActionResult Index()
        {
            return View(db.AspNetUsers.ToList());
        }
        public ActionResult Owners()
        {
            var usersWithRoleId2 = from user in db.AspNetUsers
                                   join userRole in db.AspNetUserRoles
                                   on user.Id equals userRole.UserId
                                   where userRole.RoleId == "2"
                                   select user;

            return View(usersWithRoleId2.ToList());
        }

        public ActionResult Statistics()
        {

            return View();
        }
        public ActionResult OwnersProfile()
        {
            string ownerId = User.Identity.GetUserId();
            
            /*Session["Loggedowner"].ToString();*/

            if (ownerId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            AspNetUser user = db.AspNetUsers.Find(ownerId);

            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        public ActionResult EditOwnersProfile(string id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditOwnersProfile(string id,[Bind(Include = "Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, FirstName, LastName,Phone, Customer_Img")] AspNetUser aspNetUser, HttpPostedFileBase Customer_Img)
        {
            if (ModelState.IsValid)
            {
                if (Customer_Img != null)
                {
                    Guid guid = Guid.NewGuid();
                    string path = guid + Customer_Img.FileName;
                    Customer_Img.SaveAs(Server.MapPath("../img/Customer_Img/" + path));
                    aspNetUser.Customer_Img = path;
                }
                else
                {
                    var existingModel = db.AspNetUsers.AsNoTracking().FirstOrDefault(x => x.Id == id);
                    aspNetUser.Customer_Img = existingModel.Customer_Img;
                }

                db.Entry(aspNetUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("/OwnersProfile", new { id = aspNetUser.Id});

            }
            return View(aspNetUser);
        }
        public ActionResult Customer()
        {
            var usersWithRoleId2 = from user in db.AspNetUsers
            join userRole in db.AspNetUserRoles
                                   on user.Id equals userRole.UserId
                                   where userRole.RoleId == "3"
                                   select user;

            return View(usersWithRoleId2.ToList());
        }

        public ActionResult UserProfile(string id )
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            AspNetUser user = db.AspNetUsers.Find(id);

            if (user == null)
            {
                return HttpNotFound();
            }

            // Retrieve the booking record(s) for the user
            List<Booking> bookings = db.Bookings.Where(b => b.id == id).ToList();

            // Retrieve the corresponding chalet(s), features, and images for each booking
            List<Chalet> chalets = new List<Chalet>();
            List<Feature> features = new List<Feature>();
            List<Image> images = new List<Image>();
            foreach (Booking booking in bookings)
            {
                Chalet chalet = db.Chalets.Find(booking.ChaletID);
                if (chalet != null)
                {
                    chalets.Add(chalet);
                    Feature feature = db.Features.Find(chalet.Features_ID);
                    if (feature != null)
                    {
                        features.Add(feature);
                    }
                    Image image = db.Images.Find(chalet.Images_ID);
                    if (image != null)
                    {
                        images.Add(image);
                    }
                }
            }

            var Data = Tuple.Create(user, bookings, features, images);

            return View(Data);
        }

        public ActionResult EditUserProfile(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditUserProfile(string id ,[Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName,FirstName,LastName,Phone,Customer_Img")] AspNetUser aspNetUser, HttpPostedFileBase Customer_Img)
        {
            if (ModelState.IsValid)
            {
                if (Customer_Img != null)
                {
                    Guid guid = Guid.NewGuid();
                    string path = guid + Customer_Img.FileName;
                    Customer_Img.SaveAs(Server.MapPath("../img/Customer_Img/" + path));
                    aspNetUser.Customer_Img = path;
                }
                else
                {
                    var existingModel = db.AspNetUsers.AsNoTracking().FirstOrDefault(x => x.Id == id);
                    aspNetUser.Customer_Img = existingModel.Customer_Img;
                }

                db.Entry(aspNetUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("UserProfile");
            }
            return View(aspNetUser);
        }





        // GET: AspNetUsers/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        public ActionResult OwnerDitals(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }


        // GET: AspNetUsers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AspNetUsers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName,FirstName,LastName,Customer_Img")] AspNetUser aspNetUser, HttpPostedFileBase Customer_Img)
        {
            if (ModelState.IsValid)
            {
                Guid guid = Guid.NewGuid();
                string pathMainImage = guid + Customer_Img.FileName;
                Customer_Img.SaveAs(Server.MapPath("../img/Customer_Img/" + pathMainImage));
                aspNetUser.Customer_Img = pathMainImage;


                db.AspNetUsers.Add(aspNetUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(aspNetUser);
        }

        // GET: AspNetUsers/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        // POST: AspNetUsers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id,[Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName,FirstName,LastName,Phone,Customer_Img")] AspNetUser aspNetUser , HttpPostedFileBase Customer_Img)
        {
            if (ModelState.IsValid)
            {

razansmadi/razansmadi/Views/AspNetUsers/Customer.cshtml
@model IEnumerable<razansmadi.Models.AspNetUser>

@{
    ViewBag.Title = "Customer";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<style>
    .thumbnail {
        top: -50px;
        left: -35px;
        display: block;
        z-index: 999;
        cursor: pointer;
        -webkit-transition-property: all;
        -webkit-transition-duration: 0.7s;
        -webkit-transition-timing-function: ease;
    }
        /*change the number below to scale to the appropriate size*/
        .thumbnail:hover {
            transform: scale(2);
        }

    td {
        text-align: center;
    }
</style>

<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header">
            <div class="row">
                <div class="col-sm-12">
                    <h3 class="page-title">Users</h3>

                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="datatable table table-hover table-center mb-0">
                                <thead>
                                    <tr>
                                        <th>Image</th>
                                        <th>First Name</th>
                                        <th>Last Name</th>
                                        <th>Email</th>
                                        <th>Phone Number</th>
                                        <th class="text-right"> </th>
                                    </tr>
                                </thead>

                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            <img src="~/img/Customer_Img/@item.Customer_Img" class="thumbnail" style="width:50px; height:50px; " />
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.FirstName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.LastName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Email)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Phone)
                                        </td>

                                        <td>
                                            @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-primary" })

                                        </td>

                                    </tr>
                                }
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

razansmadi/razansmadi/Views/AspNetUsers/Details.cshtml
@model razansmadi.Models.AspNetUser

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header">
            <h2>Details</h2>
            <div class="row">
                <div class="col-sm-12">
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Owners</a></li>
                        <li class="breadcrumb-item active">Details</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="page-wrapper">
            <div>
                <dl class="dl-horizontal">
                    <dt>
                       Email
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Email)
                    </dd>
                    <dt>
                        First Name
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.FirstName)
                    </dd>

                    <dt>
                     Last Name
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.LastName)
                    </dd>

                    <dt>
                       Image
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Customer_Img)
                    </dd>

                </dl>
            </div>
            <p>
                <a href="~/AspNetUsers/Index">Back to list</a>
            </p>
        </div>
    </div>
</div>

razansmadi/razansmadi/Views/AspNetUsers/UserProfile.cshtml
@model Tuple<razansmadi.Models.AspNetUser, List<razansmadi.Models.Booking> ,List<razansmadi.Models.Feature>, List < razansmadi.Models.Image >>


@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="zxx">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Aler Template">
    <meta name="keywords" content="Aler, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Owner</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700,800,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="~/template/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="~/template/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/template/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="~/template/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="~/template/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="~/template/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="~/template/css/magnific-popup.css" type="text/css">
    <link rel="stylesheet" href="~/template/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="~/template/css/style.css" type="text/css">
</head>

<body>
    <!-- Offcanvas Menu Wrapper Begin -->
    <div class="offcanvas-menu-overlay"></div>
    <div class="offcanvas-menu-wrapper">
        <div class="canvas-close">
            <span class="icon_close"></span>
        </div>
        <div class="logo">
            <a href="./index.html">
                <span style="font-family: 'Babylonica', cursive;font-weight: bolder;font-size:35px;color:#053503;">Royal Chalets</span>
            </a>
        </div>
        <div id="mobile-menu-wrap"></div>
        <div class="om-social">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-instagram"></i></a>
        </div>
    </div>
    <!-- Offcanvas Menu Wrapper End -->
    <!-- Header Section Begin -->
    <header class="header-section">
        <div class="hs-top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-2">
                        <div class="logo">
                            <a href="./index.html"><img src="img/logo.png" alt=""></a>
                        </div>
                    </div>
                </div>
                <div class="canvas-open">
                    <span class="icon_menu"></span>
                </div>
            </div>
        </div>
        <div class="hs-nav">
            <div class="d-flex justify-content-between">
                <div class="col-lg-3 logo">
                    <span style="font-family: 'Babylonica', cursive;font-weight: bolder;font-size:30px;color:#053503;">Royal Chalets</span>
                </div>
                <div class="col-lg-6">
                    <nav class="nav-menu">
                        <ul>
                            <li ><a href="./index.html">Home</a></li>
                            <li><a href="./Our Chalets.html">Chalets</a></li>
                            <li class="active"><a href="./profile.html">Profile</a></li>
                            <li><a href="./about.html">About</a></li>
                            <li><a href="./contact.html">Contact</a></li>
                            <li style="text-decoration:none; text-decoration-color:#113220;">
                                @Html.Partial("_LoginPartial")
                            </li>
                        </ul>
                    </nav>
                </div>
                <div class="col-lg-3">
                    <div class="hn-social">
                        <a href="https://www.facebook.com" target="_blank"><i class="fa fa-facebook"></i></a>
                        <a href="https://twitter.com" target="_blank"><i class="fa fa-twitter"></i></a>
                        <a href="https://www.instagram.com/" target="_blank"><i class="fa fa-instagram"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Header End -->
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section spad set-bg" data-setbg="@Url.Content("~/img/beautiful-park.jpg")">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb-text">
                        <h4>Profile</h4>
                        <div class="bt-option">
                            <a href="./index.html"><i class="fa fa-home"></i> Home</a>
                            <a href="./agents.html">Profile</a>
                            <span>@Model.Item1.FirstName @Model.Item1.LastName</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->
    <!-- Profile Section Begin -->
    <section class="profile-section spad">
        <div class="container">
            <div class="profile-agent-content">
                <div class="row">
                    <div class="col-lg-5">
                        <div class="profile-agent-info">
                            <div class="pi-pic">
                                <img src="~/img/agents/@Model.Item1.Customer_Img" alt="user Img">
                            </div>
                            <div class="pi-text">
                                <br />
                                <h5>@Model.Item1.FirstName @Model.Item1.LastName </h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-5">
                        <div class="profile-agent-widget">
                            <ul>
                                <li>Email <span>@Model.Item1.Email  </span></li>
                                <li>Phone <span>@Model.Item1.PhoneNumber</span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-2 text-center">
                        @Html.ActionLink("Edit", "EditUserProfile", "AspNetUsers", new { id = 1 }, new { @class = "btn btn-success mt-3" })
                    </div>

                </div>
            </div>
        </div>
    </section>
    <br />
    <br />
    <!-- Profile Section End -->
    <!-- Property Section Begin -->

    @*<section class="property-section profile-page spad">
        <div style="display:flex;justify-content:center"> <button type="button" class="btn btn-success">Your Previous Reservations</button> <br /><br /></div>

        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6 mix all house">
                    <div class="property-item">
                        @foreach (var c in Model.Item4)
                        {
                            <d class="pi-pic set-bg" data-setbg="~/img/northfarm/@c.MainImage"> </d>
                        }

                        @foreach (var c in Model.Item2)
                        {
                            <div class="pi-text">
                                <a href="#" class="heart-icon"></a>
                                <div class="pt-price">Start From @c.Chalet.PricePerNight JD /Day </div>
                                <h5>@c.Chalet.Chalet_Name</h5>
                                <p><span class="icon_pin_alt"></span> @c.Chalet.Chalet_Address</p>
                                <ul>
                                    <li><i class="fa fa-object-group"></i>@c.Chalet.area </li>
                                    <li><i class="fa fa-bathtub"></i>@c.Chalet.bathroom</li>
                                    <li><i class="fa fa-bed"></i>@c.Chalet.bedroom</li>

                                    @foreach (var a in Model.Item3)
                                    {
                                        <li><i class="fa fa-automobile"></i>@a.Carpark</li>

                                    }
                                </ul>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </section>*@
    <!-- Property Section End -->
    <!-- Footer Section Begin -->
    <footer class="footer-section">
        <div class="container">
            <div class="d-flex justify-content-between ">
                <div class="col-lg-4 col-md-6">
                    <div class="fs-about">
                        <div class="fs-logo">
                            <a href="#">
                                <span style="font-family: 'Babylonica', cursive;font-weight: bolder;font-size:70px;color:#053503;">Royal Chalets</span>
                            </a>
                        </div>
                        <p>
                            Comfortable and convenient to Enjoy the beauty of Jerash's stunning nature
                        </p>
                        <div class="fs-social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 d-none d-md-block">
                    <div class="fs-widget">
                        <h5>Links</h5>
                        <div class="d-flex">
                            <ul class="col-6">
                                <li><a href="#">Contact us</a></li>
                                <li><a href="#">About us</a></li>
                                <li><a href="#">Register</a></li>
                            </ul>
                            <ul class="col-6">
                                <li><a href="#">All Chalets</a></li>
                                <li><a href="#">Rent your Chalets</a></li>
                                <li><a href="#">Login</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="d-block d-sm-none">
                    <div class="fs-widget">
                        <h5 class="d-flex justify-content-center">Links</h5>
                        <div class="d-flex">
                            <ul class="col-6">
                                <li><a href="#">Contact</a></li>
                                <li><a href="#">About</a></li>
                                <li><a href="#">Register</a></li>
                                <li><a href="#">Chalets</a></li>
                                <li><a href="#">Login</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
            <div class="copyright-text">
                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> All rights reserved.
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->
    <!-- Js Plugins -->
    <script src="~/template/js/jquery-3.3.1.min.js"></script>
    <script src="~/template/js/bootstrap.min.js"></script>
    <script src="~/template/js/jquery.magnific-popup.min.js"></script>
    <script src="~/template/js/mixitup.min.js"></script>
    <script src="~/template/js/jquery-ui.min.js"></script>
    <script src="~/template/js/jquery.nice-select.min.js"></script>
    <script src="~/template/js/jquery.slicknav.js"></script>
    <script src="~/template/js/owl.carousel.min.js"></script>
    <script src="~/template/js/jquery.richtext.min.js"></script>
    <script src="~/template/js/image-uploader.min.js"></script>
    <script src="~/template/js/main.js"></script>
</body>

</html>